INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (1, ,, 10);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (2, 'Jalapenos, Mushroom, Olive', 10);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (3, 'Chicken, Mushroom, Pineapple', 10);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (4, 'Ham, Beef, Bacon', 12);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (5, 'Jalapenos, Mushroom, Olive', 12);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (6, 'Chicken, Mushroom, Pineapple', 12);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (7, 'Ham, Beef, Bacon', 14);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (8, 'Jalapenos, Mushroom, Olive', 14);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (9, 'Chicken, Mushroom, Pineapple', 14);
INSERT INTO pizza_specialty (crust_type, toppings, price) VALUES (10, 'Its a secret', 16);
